#!/bin/sh

set -e -u -x

PYS=$(py3versions -s)

cp -r tests "$AUTOPKGTEST_TMP"
cd "$AUTOPKGTEST_TMP"

for py in $PYS; do
    echo "Testing with $py:"
    timeout 300 $py -m pytest -v -k 'not test_init_ipc_socket'
done
